/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai_3;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DINH
 */
public class Form_Bai3 extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel;
    String hoTen, ngaySinh, diaChi, gioiTinh, phongBan;
    int thamNien, heSoLuong;
    long luongCoBan, thucLinh;
    NhanVien nv;
    ArrayList<NhanVien> dsNV = new ArrayList<>();
    
    public void khoiTao(){
        try {
            hoTen = hoTen_txt.getText();
            ngaySinh = ngaySinh_txt.getText();
            diaChi = diaChi_txt.getText();
            if(nam_button.isSelected()){
                gioiTinh = "Nam";
            } else {
                gioiTinh = "Nữ";
            }
            phongBan = String.valueOf(phongBan_comboBox.getSelectedItem());
            heSoLuong = Integer.parseInt(heSoLuong_txt.getText());
            thamNien = Integer.parseInt(thamNien_txt.getText());
            luongCoBan =  Long.parseLong(luongCoban_txt.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Nhập sai định dạng dữ liệu!");
        }
        nv = new NhanVien(phongBan, heSoLuong, thamNien, luongCoBan, 
                hoTen, ngaySinh, diaChi, gioiTinh);
        
    }

    /**
     * Creates new form Form     
     */
    public Form_Bai3() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hoTen_txt = new javax.swing.JTextField();
        ngaySinh_txt = new javax.swing.JTextField();
        diaChi_txt = new javax.swing.JTextField();
        heSoLuong_txt = new javax.swing.JTextField();
        luongCoban_txt = new javax.swing.JTextField();
        thamNien_txt = new javax.swing.JTextField();
        phongBan_comboBox = new javax.swing.JComboBox<>();
        Them_Button = new javax.swing.JButton();
        Luu_Button = new javax.swing.JButton();
        nam_button = new javax.swing.JRadioButton();
        nu_button = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhanVien_table = new javax.swing.JTable();
        docDuLieu_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ tên");

        jLabel2.setText("Ngày Sinh");

        jLabel3.setText("Địa chỉ");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Phòng ban");

        jLabel6.setText("Hệ số lương");

        jLabel7.setText("Thâm niên");

        jLabel8.setText("Lương cơ bản");

        phongBan_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiết bị", "Nhân sự", "R&D", "Kinh doanh" }));

        Them_Button.setText("Thêm Nhân Viên");
        Them_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Them_ButtonActionPerformed(evt);
            }
        });

        Luu_Button.setText("Lưu Dữ Liệu");
        Luu_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Luu_ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nam_button);
        nam_button.setText("Nam");

        buttonGroup1.add(nu_button);
        nu_button.setText("Nữ");

        nhanVien_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(nhanVien_table);

        docDuLieu_button.setText("Đọc Dữ Liệu");
        docDuLieu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docDuLieu_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoTen_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngaySinh_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaChi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heSoLuong_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(luongCoban_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thamNien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phongBan_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nam_button)
                                .addGap(18, 18, 18)
                                .addComponent(nu_button))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Them_Button)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(docDuLieu_button)
                                    .addComponent(Luu_Button))))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(hoTen_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ngaySinh_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(diaChi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nam_button)
                            .addComponent(nu_button))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(phongBan_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heSoLuong_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(thamNien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(luongCoban_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(Them_Button)))
                .addGap(18, 18, 18)
                .addComponent(Luu_Button)
                .addGap(18, 18, 18)
                .addComponent(docDuLieu_button)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Them_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Them_ButtonActionPerformed
        // TODO add your handling code here:
        khoiTao();
        System.out.println(nv);
        dsNV.add(nv);
        
    }//GEN-LAST:event_Them_ButtonActionPerformed

    private void Luu_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Luu_ButtonActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter fw = new FileWriter("NhanVien_B3.dat");
            for(NhanVien x:dsNV){
                fw.write(x.toString());
            }
            fw.close();
            JOptionPane.showMessageDialog(this, "Lưu file thành công !");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_Luu_ButtonActionPerformed

    private void docDuLieu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docDuLieu_buttonActionPerformed
        // TODO add your handling code here:
        defaultTableModel = new DefaultTableModel(new Object[]{"Họ tên","Ngày sinh","Địa chỉ", "Giới Tính", "Phòng ban"
            ,"Hệ Số lương","Thâm Niên","Lương cơ bản", "Thực Lĩnh"},0);
        nhanVien_table.setModel(defaultTableModel);
        try {
            FileReader fr = new FileReader("NhanVien_B3.dat");
            BufferedReader br = new BufferedReader(fr);
            String line;
            while((line=br.readLine()) != null){
                String a[] = line.split("\\$");
                defaultTableModel.addRow(a);
            }
            br.close();
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_docDuLieu_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Bai3().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Luu_Button;
    private javax.swing.JButton Them_Button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diaChi_txt;
    private javax.swing.JButton docDuLieu_button;
    private javax.swing.JTextField heSoLuong_txt;
    private javax.swing.JTextField hoTen_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField luongCoban_txt;
    private javax.swing.JRadioButton nam_button;
    private javax.swing.JTextField ngaySinh_txt;
    private javax.swing.JTable nhanVien_table;
    private javax.swing.JRadioButton nu_button;
    private javax.swing.JComboBox<String> phongBan_comboBox;
    private javax.swing.JTextField thamNien_txt;
    // End of variables declaration//GEN-END:variables
}
