/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai_5;

import Bai_3.NhanVien;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.shape.SVGPath;
import javax.swing.JOptionPane;
import sun.awt.FwDispatcher;

/**
 *
 * @author DINH
 */
public class Form_B5 extends javax.swing.JFrame {
    String maSinhVien,hoTen,ngaySinh,gioiTinh,donVi;
    double diemTB;
    double hocPhi,luong;
    SinhVien sv;
    public void khoiTao(){
            maSinhVien = maSinhVien_txt.getText();
            hoTen = hoTen_txt.getText();
            ngaySinh = ngaySinh_txt.getText();
            gioiTinh = cbo_gt.getSelectedItem().toString();
            diemTB = Double.parseDouble(diemTB_txt.getText());
            if(sinhVien_comBoBox.getSelectedIndex()==0){
                hocPhi = Double.parseDouble(hocPhi_txt.getText());
            } else {
                luong = Double.parseDouble(luong_txt.getText());
                donVi = donVi_txt.getText();
            }
        
    }
    /**
     * Creates new form Form_B5
     */
    public Form_B5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        donVi_lable = new javax.swing.JLabel();
        maSinhVien_txt = new javax.swing.JTextField();
        hoTen_txt = new javax.swing.JTextField();
        ngaySinh_txt = new javax.swing.JTextField();
        hocPhi_txt = new javax.swing.JTextField();
        luong_lable = new javax.swing.JLabel();
        luong_txt = new javax.swing.JTextField();
        donVi_txt = new javax.swing.JTextField();
        diemTB_txt = new javax.swing.JTextField();
        sinhVien_comBoBox = new javax.swing.JComboBox<>();
        luuDuLieu_button = new javax.swing.JButton();
        cbo_gt = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sinh viên");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Điển trung bình");

        jLabel6.setText("Sinh viên");

        jLabel7.setText("Học phí");

        donVi_lable.setText("Đơn vị");

        luong_lable.setText("Lương");

        sinhVien_comBoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinh Viên HTTT", "Sinh Viên Mật Mã" }));
        sinhVien_comBoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhVien_comBoBoxActionPerformed(evt);
            }
        });

        luuDuLieu_button.setText("Lưu Dữ Liệu");
        luuDuLieu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuDuLieu_buttonActionPerformed(evt);
            }
        });

        cbo_gt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ngaySinh_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hoTen_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maSinhVien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sinhVien_comBoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diemTB_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luong_lable)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(donVi_lable)
                                        .addComponent(jLabel7)))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luong_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hocPhi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(donVi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(luuDuLieu_button)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sinhVien_comBoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maSinhVien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(hoTen_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ngaySinh_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbo_gt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(diemTB_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(donVi_lable)
                        .addGap(18, 18, 18)
                        .addComponent(luong_lable))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hocPhi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(donVi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(luong_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(luuDuLieu_button)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luuDuLieu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuDuLieu_buttonActionPerformed
        // TODO add your handling code here:
        khoiTao();
        try {
            FileWriter fw;
            File f1 = new File("SinhVienHTTT.dat");
            File f2 = new File("SinhVienMatMa.dat");
            if(sinhVien_comBoBox.getSelectedIndex()==0){
                sv = new SinhVienHTTT(donVi, hoTen, ngaySinh, gioiTinh, diemTB, hocPhi);
                fw = new FileWriter(f1,true);
            } else {
                sv = new SinhVienMatMa(donVi, hoTen, ngaySinh, gioiTinh, diemTB, donVi, luong);
                fw = new FileWriter(f2,true);
            }
            fw.write(sv.toString());
            fw.write("\n");
            fw.close();
            JOptionPane.showMessageDialog(null,"Lưu File thành công!");
            
        } catch (IOException ex) {
            Logger.getLogger(Form_B5.class.getName()).log(Level.SEVERE, null, ex);
        } 
       
        
    }//GEN-LAST:event_luuDuLieu_buttonActionPerformed

    private void sinhVien_comBoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhVien_comBoBoxActionPerformed
        // TODO add your handling code here:
        if(sinhVien_comBoBox.getSelectedIndex()==0){
            hocPhi_txt.setEnabled(true);
            donVi_txt.setEnabled(false);
            luong_txt.setEnabled(false);
        } else {
            hocPhi_txt.setEnabled(false);
            donVi_txt.setEnabled(true);
            luong_txt.setEnabled(true);
        }
    }//GEN-LAST:event_sinhVien_comBoBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_B5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_B5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_B5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_B5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_B5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_gt;
    private javax.swing.JTextField diemTB_txt;
    private javax.swing.JLabel donVi_lable;
    private javax.swing.JTextField donVi_txt;
    private javax.swing.JTextField hoTen_txt;
    private javax.swing.JTextField hocPhi_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel luong_lable;
    private javax.swing.JTextField luong_txt;
    private javax.swing.JButton luuDuLieu_button;
    private javax.swing.JTextField maSinhVien_txt;
    private javax.swing.JTextField ngaySinh_txt;
    private javax.swing.JComboBox<String> sinhVien_comBoBox;
    // End of variables declaration//GEN-END:variables
}
